language: python
python:
  # 3.4 doesn't have enum.Enum.auto(). Re-enable it if we decide to use aenum instead.
  # - 3.4
  - 3.6
  - 3.8

# Windows setup
matrix:
  include:
      - name: "Python 3.7.4 on Windows"
        os: windows           # Windows 10.0.17134 N/A Build 17134
        language: shell       # 'language: python' is an error on Travis CI Windows
        before_install:
          - choco install python --version 3.7.4
          - python --version
          - python -m pip install --upgrade pip
          - pip3 install --upgrade pytest
          - pip3 install --upgrade pytest-cov
        env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
install:
  - pip install -e .
script:
  - python3 setup.py test
after_success:
  # submit coverage
  - bash <(curl -s https://codecov.io/bash)
