language: python
python:
  - 3.4
  - 3.6
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install coverage
install:
  # - pip install ".[test]" . # install package + test dependencies
  - pip install -e .
script:
  - python3 setup.py test
  - coverage run -m setup.py test
after_success:
  - codecov # submit coverage
  - bash <(curl -s https://codecov.io/bash)
