language: python
python:
  # 3.4 doesn't have enum.Enum.auto(). Re-enable it if we decide to use aenum instead.
  # - 3.4
  - 3.6
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
install:
  - pip install -e .
script:
  - python3 setup.py test
after_success:
  # submit coverage
  - bash <(curl -s https://codecov.io/bash)
