#! /usr/bin/env python3
"""
Autokey needs to be running.
autokey-run should be in your path, otherwise it is in the main autokey
folder.
Usage:
Add this adapter folder.
Add this script into autokey under the description "bindings" then run:  autokey-run -s bindings
"""
import autokey.iomediator
import autokey.configmanager
import autokey.scripting
# import autokey.scripting_highlevel as hl
# system = autokey.scripting.System()
create_hotkey = autokey.scripting.Engine.create_hotkey
create_hotkey = engine.create_hotkey
folder = engine.get_folder("autokey_univisal")

create_hotkey(folder, "a", [], "a", "<script name=univi args=a>", temporary=True)
create_hotkey(folder, "b", [], "b", "<script name=univi args=b>", temporary=True)
create_hotkey(folder, "c", [], "c", "<script name=univi args=c>", temporary=True)
create_hotkey(folder, "d", [], "d", "<script name=univi args=d>", temporary=True)
create_hotkey(folder, "e", [], "e", "<script name=univi args=e>", temporary=True)
create_hotkey(folder, "f", [], "f", "<script name=univi args=f>", temporary=True)
create_hotkey(folder, "g", [], "g", "<script name=univi args=g>", temporary=True)
create_hotkey(folder, "h", [], "h", "<script name=univi args=h>", temporary=True)
create_hotkey(folder, "i", [], "i", "<script name=univi args=i>", temporary=True)
create_hotkey(folder, "j", [], "j", "<script name=univi args=j>", temporary=True)
create_hotkey(folder, "k", [], "k", "<script name=univi args=k>", temporary=True)
create_hotkey(folder, "l", [], "l", "<script name=univi args=l>", temporary=True)
create_hotkey(folder, "m", [], "m", "<script name=univi args=m>", temporary=True)
create_hotkey(folder, "n", [], "n", "<script name=univi args=n>", temporary=True)
create_hotkey(folder, "o", [], "o", "<script name=univi args=o>", temporary=True)
create_hotkey(folder, "p", [], "p", "<script name=univi args=p>", temporary=True)
create_hotkey(folder, "q", [], "q", "<script name=univi args=q>", temporary=True)
create_hotkey(folder, "r", [], "r", "<script name=univi args=r>", temporary=True)
create_hotkey(folder, "s", [], "s", "<script name=univi args=s>", temporary=True)
create_hotkey(folder, "t", [], "t", "<script name=univi args=t>", temporary=True)
create_hotkey(folder, "u", [], "u", "<script name=univi args=u>", temporary=True)
create_hotkey(folder, "v", [], "v", "<script name=univi args=v>", temporary=True)
create_hotkey(folder, "w", [], "w", "<script name=univi args=w>", temporary=True)
create_hotkey(folder, "x", [], "x", "<script name=univi args=x>", temporary=True)
create_hotkey(folder, "y", [], "y", "<script name=univi args=y>", temporary=True)
create_hotkey(folder, "z", [], "z", "<script name=univi args=z>", temporary=True)
create_hotkey(folder, "A", ["<shift>"], "A", "<script name=univi args=A>", temporary=True)
create_hotkey(folder, "B", ["<shift>"], "B", "<script name=univi args=B>", temporary=True)
create_hotkey(folder, "C", ["<shift>"], "C", "<script name=univi args=C>", temporary=True)
create_hotkey(folder, "D", ["<shift>"], "D", "<script name=univi args=D>", temporary=True)
create_hotkey(folder, "E", ["<shift>"], "E", "<script name=univi args=E>", temporary=True)
create_hotkey(folder, "F", ["<shift>"], "F", "<script name=univi args=F>", temporary=True)
create_hotkey(folder, "G", ["<shift>"], "G", "<script name=univi args=G>", temporary=True)
create_hotkey(folder, "H", ["<shift>"], "H", "<script name=univi args=H>", temporary=True)
create_hotkey(folder, "I", ["<shift>"], "I", "<script name=univi args=I>", temporary=True)
create_hotkey(folder, "J", ["<shift>"], "J", "<script name=univi args=J>", temporary=True)
create_hotkey(folder, "K", ["<shift>"], "K", "<script name=univi args=K>", temporary=True)
create_hotkey(folder, "L", ["<shift>"], "L", "<script name=univi args=L>", temporary=True)
create_hotkey(folder, "M", ["<shift>"], "M", "<script name=univi args=M>", temporary=True)
create_hotkey(folder, "N", ["<shift>"], "N", "<script name=univi args=N>", temporary=True)
create_hotkey(folder, "O", ["<shift>"], "O", "<script name=univi args=O>", temporary=True)
create_hotkey(folder, "P", ["<shift>"], "P", "<script name=univi args=P>", temporary=True)
create_hotkey(folder, "Q", ["<shift>"], "Q", "<script name=univi args=Q>", temporary=True)
create_hotkey(folder, "R", ["<shift>"], "R", "<script name=univi args=R>", temporary=True)
create_hotkey(folder, "S", ["<shift>"], "S", "<script name=univi args=S>", temporary=True)
create_hotkey(folder, "T", ["<shift>"], "T", "<script name=univi args=T>", temporary=True)
create_hotkey(folder, "U", ["<shift>"], "U", "<script name=univi args=U>", temporary=True)
create_hotkey(folder, "V", ["<shift>"], "V", "<script name=univi args=V>", temporary=True)
create_hotkey(folder, "W", ["<shift>"], "W", "<script name=univi args=W>", temporary=True)
create_hotkey(folder, "X", ["<shift>"], "X", "<script name=univi args=X>", temporary=True)
create_hotkey(folder, "Y", ["<shift>"], "Y", "<script name=univi args=Y>", temporary=True)
create_hotkey(folder, "Z", ["<shift>"], "Z", "<script name=univi args=Z>", temporary=True)
create_hotkey(folder, "0", [], "0", "<script name=univi args=0>", temporary=True)
create_hotkey(folder, "1", [], "1", "<script name=univi args=1>", temporary=True)
create_hotkey(folder, "2", [], "2", "<script name=univi args=2>", temporary=True)
create_hotkey(folder, "3", [], "3", "<script name=univi args=3>", temporary=True)
create_hotkey(folder, "4", [], "4", "<script name=univi args=4>", temporary=True)
create_hotkey(folder, "5", [], "5", "<script name=univi args=5>", temporary=True)
create_hotkey(folder, "6", [], "6", "<script name=univi args=6>", temporary=True)
create_hotkey(folder, "7", [], "7", "<script name=univi args=7>", temporary=True)
create_hotkey(folder, "8", [], "8", "<script name=univi args=8>", temporary=True)
create_hotkey(folder, "9", [], "9", "<script name=univi args=9>", temporary=True)
create_hotkey(folder, "!", [], "!", "<script name=univi args=!>", temporary=True)
create_hotkey(folder, "#", [], "#", "<script name=univi args=#>", temporary=True)
create_hotkey(folder, "$", [], "$", "<script name=univi args=$>", temporary=True)
create_hotkey(folder, "%", [], "%", "<script name=univi args=%>", temporary=True)
create_hotkey(folder, "&", [], "&", "<script name=univi args=&>", temporary=True)
create_hotkey(folder, "(", [], "(", "<script name=univi args=(>", temporary=True)
create_hotkey(folder, ")", [], ")", "<script name=univi args=)>", temporary=True)
create_hotkey(folder, "*", [], "*", "<script name=univi args=*>", temporary=True)
create_hotkey(folder, "+", [], "+", "<script name=univi args=+>", temporary=True)
create_hotkey(folder, ",", [], ",", "<script name=univi args=,>", temporary=True)
create_hotkey(folder, "-", [], "-", "<script name=univi args=->", temporary=True)
create_hotkey(folder, ".", [], ".", "<script name=univi args=.>", temporary=True)
create_hotkey(folder, "/", [], "/", "<script name=univi args=/>", temporary=True)
create_hotkey(folder, ":", [], ":", "<script name=univi args=:>", temporary=True)
create_hotkey(folder, ";", [], ";", "<script name=univi args=;>", temporary=True)
create_hotkey(folder, "<", [], "<", "<script name=univi args=<>", temporary=True)
create_hotkey(folder, "=", [], "=", "<script name=univi args==>", temporary=True)
create_hotkey(folder, ">", [], ">", "<script name=univi args=>>", temporary=True)
create_hotkey(folder, "?", [], "?", "<script name=univi args=?>", temporary=True)
create_hotkey(folder, "@", [], "@", "<script name=univi args=@>", temporary=True)
create_hotkey(folder, "[", [], "[", "<script name=univi args=[>", temporary=True)
create_hotkey(folder, "]", [], "]", "<script name=univi args=]>", temporary=True)
create_hotkey(folder, "^", [], "^", "<script name=univi args=^>", temporary=True)
create_hotkey(folder, "_", [], "_", "<script name=univi args=_>", temporary=True)
create_hotkey(folder, "`", [], "`", "<script name=univi args=`>", temporary=True)
create_hotkey(folder, "{", [], "{", "<script name=univi args={>", temporary=True)
create_hotkey(folder, "|", [], "|", "<script name=univi args=|>", temporary=True)
create_hotkey(folder, "}", [], "}", "<script name=univi args=}>", temporary=True)
create_hotkey(folder, "~", [], "~", "<script name=univi args=~>", temporary=True)
create_hotkey(folder, "<escape>", [], "<escape>", "<script name=univi args=esc>", temporary=True)
create_hotkey(folder, "\\", [], "\\", "<script name=univi args=\>", temporary=True)
create_hotkey(folder, "\'", [], "\'", "<script name=univi args=\'>", temporary=True)
create_hotkey(folder, "\"", [], "\"", "<script name=univi args=\">", temporary=True)
